name: CI - Test y Build React App

on: [push, pull_request]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          cd client
          npm install

      - name: Ejecutar pruebas
        run: |
          cd client
          npm test

      - name: Construir la aplicación
        run: |
          cd client
          npm run build
